### ISSUE TITLE
Cannot Install on Windows

### ISSUE THREAD

**Issue by lsutton00** [ConduitVC/aws-utils#149]
I tried to install on windows and got this error:

`> download --extract -o emulator https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip && ./install.sh

'.' is not recognized as an internal or external command,
operable program or batch file.`

It seems to be a problem with ./install which should be .\install for windows. 
Is there any way I can fix/work around this?

**Comment by cbaron** [comment]
Take a look at the [installation](https://github.com/ConduitVC/aws-utils/tree/master/packages/appsync-emulator-serverless#installation) instructions for the package.

I would suggest installing dynamodb manually based on other instructions, although you're welcome to make a PR so that it works for windows automatically.

Then you can install the emulator and skip the dynamo emulator install:

```
npm i @conduitvc/appsync-emulator-serverless [--no-optional]
```
